#!/bin/bash
#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
# 
#    http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 
#

shopt -s expand_aliases
export PATH=/usr/local/tika:${PATH}
alias tika="java -jar /usr/local/tika/tika-app-1.3.jar"

BASE_URL="http://geodynamics.org/cig/software"
CIG_BASE_URL="http://geodynamics.org/"

CIG_SOFTWARE_NAMES=`tika "${BASE_URL}" | grep rect | grep software | cut -d">" -f2 | cut -d"<" -f1 | sort | uniq | perl -pi -e 's/^\n$//' | grep -v "For descriptions"`

for name in $CIG_SOFTWARE_NAMES; do
    lc=`echo $name | perl -ne 'print lc'`
    URL_LIST=`tika "${BASE_URL}/${lc}" | grep tgz | cut -d\" -f4`
    URLS=`echo "$URLS $URL_LIST"`
done

mkdir -p download
URL_LIST=`echo $URL_LIST | cut -d" " -f1-`
for url in $URLS; do
    DURL="$CIG_BASE_URL$url"
    cd download
    curl -O $DURL
    cd ..
done

